### ISSUE TITLE
Munki Import throws python warnings with autopkg

### ISSUE THREAD

**Issue by qgreen63** [SimpleMDM/munki-plugin#9]
Using the plugin to import apps using autopkg throws the following warnings:

/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:956: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:961: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)

**Comment by eddiekelley** [comment]
I can confirm that this is fixed by PR #10.
